FROM node:22

WORKDIR /user/src/app

COPY package.json package-lock.json turbo.json ./
COPY apps ./apps
COPY packages ./packages

RUN npm install

RUN npm run db:migrate

RUN npm run build

CMD [ "npm", "run", "start-user-app" ]