name: Build on PR

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      
      - name: Install Dependencies
        run: npm install

      - name: Migrate drizzle
        run: npm run db:migrate
        
      - name: Run Build
        run: npm run build
        env:
          DATABASE_URL: "postgresql://dummy:dummy@localhost:5432/dummy"
          NEXTAUTH_SECRET: "dummy-secret-for-build"
          NEXTAUTH_URL: "http://localhost:3000"
          GOOGLE_CLIENT_ID: "dummy-google-client-id"
          GOOGLE_CLIENT_SECRET: "dummy-google-client-secret"
